package src.com.java.hr.model;
// Generated Mar 12, 2023 8:28:32 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HrsDepartment generated by hbm2java
 */
@Entity
@Table(name = "HRS_DEPARTMENT",
         schema = "HR_SERVE"
)
public class HrsDepartment implements java.io.Serializable
{

    private BigDecimal departmentPk;
    private String departmentName;
    private Set hrsEmployeeses = new HashSet(0);

    public HrsDepartment()
    {
    }

    public HrsDepartment(BigDecimal departmentPk)
    {
        this.departmentPk = departmentPk;
    }

    public HrsDepartment(BigDecimal departmentPk, String departmentName, Set hrsEmployeeses)
    {
        this.departmentPk = departmentPk;
        this.departmentName = departmentName;
        this.hrsEmployeeses = hrsEmployeeses;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "DEPARTMENT_PK", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getDepartmentPk()
    {
        return this.departmentPk;
    }

    public void setDepartmentPk(BigDecimal departmentPk)
    {
        this.departmentPk = departmentPk;
    }

    @Column(name = "DEPARTMENT_NAME", length = 100)
    public String getDepartmentName()
    {
        return this.departmentName;
    }

    public void setDepartmentName(String departmentName)
    {
        this.departmentName = departmentName;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "hrsDepartment",targetEntity = HrsEmployees.class)
    public Set getHrsEmployeeses()
    {
        return this.hrsEmployeeses;
    }

    public void setHrsEmployeeses(Set hrsEmployeeses)
    {
        this.hrsEmployeeses = hrsEmployeeses;
    }

}
